<?php

namespace App\DataFixtures;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;
use App\Entity\Page;
use App\Entity\Section;

class SectionFixtures extends Fixture implements DependentFixtureInterface
{
  const SECTIONS = [
    ["name" => "Section home-bannière", "page" => 1],
    ["name" => "Section home-1", "page" => 1],
    ["name" => "Section home-2", "page" => 1],
    ["name" => "Section home-3", "page" => 1],
    ["name" => "Section home-4", "page" => 1],
    ["name" => "Section home-5", "page" => 1],
    ["name" => "Section home-6", "page" => 1],
    ["name" => "Section LO-bannière", "page" => 2],
    ["name" => "Section LO-1", "page" => 2],
    ["name" => "Section LO-2", "page" => 2],
    ["name" => "Section PO-bannière", "page" => 3],
    ["name" => "Section PO-1", "page" => 3],
    ["name" => "Section PO-2", "page" => 3],
    ["name" => "Section PO-3", "page" => 3],
    ["name" => "Section PO-4", "page" => 3],
    ["name" => "Section PM-bannière", "page" => 4],
    ["name" => "Section PM-1", "page" => 4],
    ["name" => "Section PM-2", "page" => 4],
    ["name" => "Section PM-3", "page" => 4],
    ["name" => "Section PM-4", "page" => 4],
    ["name" => "Section PM-5", "page" => 4],
    ["name" => "Section FP-bannière", "page" => 5],
    ["name" => "Section FP-1", "page" => 5],
    ["name" => "Section FP-C-1", "page" => 5],
    ["name" => "Section FP-C-2", "page" => 5],
    ["name" => "Section FP-C-3", "page" => 5],
    ["name" => "Section FP-2", "page" => 5],
    ["name" => "Section FP-3", "page" => 5],
    ["name" => "Section FP-C-3", "page" => 5],
    ["name" => "Section FP-4", "page" => 5],
    ["name" => "Section FP-5", "page" => 5],
    ["name" => "Section FP-6", "page" => 5],
    ["name" => "Section FP-7", "page" => 5],
    ["name" => "Section FP-8", "page" => 5],
    ["name" => "Section FP-9", "page" => 5],
    ["name" => "Section FP-10", "page" => 5],
    ["name" => "Section FP-11", "page" => 5],
    ["name" => "Section FP-12", "page" => 5],
    ["name" => "Section FP-13", "page" => 5],
    ["name" => "Section FP-14", "page" => 5],
    ["name" => "Section FP-15", "page" => 5],
    ["name" => "Section FP-16", "page" => 5],
    ["name" => "Section FP-17", "page" => 5],
    ["name" => "Section FP-18", "page" => 5],
    ["name" => "Section FP-19", "page" => 5],
    ["name" => "Section FP-20", "page" => 5],
    ["name" => "Section FP-21", "page" => 5],
    ["name" => "Section FP-22", "page" => 5],
    ["name" => "Section FP-23", "page" => 5],
    ["name" => "Section FP-24", "page" => 5],
    ["name" => "Section QSN-bannière", "page" => 6],
    ["name" => "Section QSN-1", "page" => 6],
    ["name" => "Section QSN-2", "page" => 6],
    ["name" => "Section QSN-3", "page" => 6],
    ["name" => "Section QSN-4", "page" => 6],
    ["name" => "Section PDC-bannière", "page" => 7],
    ["name" => "Section PDC-1", "page" => 7],
    ["name" => "Section faqs-bannière", "page" => 8],
    ["name" => "Section faqs-1", "page" => 8],
    ["name" => "Section ML-bannière", "page" => 9],
    ["name" => "Section ML-1", "page" => 9],
    ["name" => "Section CGV-bannière", "page" => 10],
    ["name" => "Section CGV-1", "page" => 10],
    ["name" => "section NC-bannière", "page" => 11],
    ["name" => "Section bfn-bannière", "page" => 12],
    ["name" => "Section bfn-1", "page" => 12],
    ["name" => "Section bfn-2", "page" => 12],
    ["name" => "Section bfn-3", "page" => 12],
    ["name" => "Section bfn-4", "page" => 12],
    ["name" => "Section bfn-5", "page" => 12],
    ["name" => "Section bfp-bannière", "page" => 13],
    ["name" => "Section bfp-1", "page" => 13],
    ["name" => "Section bfp-2", "page" => 13],
    ["name" => "Section bfp-3", "page" => 13],
    ["name" => "Section bfp-4", "page" => 13],
    ["name" => "Section bfp-5", "page" => 13],
    ["name" => "Section bfp-6", "page" => 13],
    ["name" => "Section bfp-7", "page" => 13],
    ["name" => "Section ME-bannière", "page" => 14],
    ["name" => "Section ME-1", "page" => 14],
    ["name" => "Section ME-2", "page" => 14],
    ["name" => "Section STBA-bannière", "page" => 15],
    ["name" => "Section STBA-1", "page" => 15],
    ["name" => "Section BB-bannière", "page" => 16],
    ["name" => "Section BB-1", "page" => 16],
    ["name" => "Section BB-2", "page" => 16],
    ["name" => "Section BB-3", "page" => 16],
    ["name" => "Section BB-4", "page" => 16],
    ["name" => "Section BB-5", "page" => 16],
    ["name" => "Section BB-6", "page" => 16],
    ["name" => "Section CDN-bannière", "page" => 17],
    ["name" => "Section CDN-1", "page" => 17],
    ["name" => "Section CDN-2", "page" => 17],
    ["name" => "Section CDN-3", "page" => 17],
    ["name" => "Section CDN-4", "page" => 17],
    ["name" => "Section CDN-5", "page" => 17],
    ["name" => "Section HYP-bannière", "page" => 18],
    ["name" => "Section HYP-1", "page" => 18],
    ["name" => "Section HYP-2", "page" => 18],
    ["name" => "Section HYP-3", "page" => 18],
    ["name" => "Section DHB-bannière", "page" => 19],
    ["name" => "Section DHB-1", "page" => 19],
    ["name" => "Section DHB-2", "page" => 19],
    ["name" => "Section DHB-3", "page" => 19],
    ["name" => "Section DHB-4", "page" => 19],
    ["name" => "Section AG-bannière", "page" => 20],
    ["name" => "Section AG-1", "page" => 20],
    ["name" => "Section AG-2", "page" => 20],
    ["name" => "Section AG-3", "page" => 20],
    ["name" => "Section AG-4", "page" => 20],
    ["name" => "Section MV-bannière", "page" => 21],
    ["name" => "Section MV-1", "page" => 21],
    ["name" => "Section MV-2", "page" => 21],
    ["name" => "Section MV-3", "page" => 21],
    ["name" => "Section MV-4", "page" => 21],
    ["name" => "Section SA-bannière", "page" => 22],
    ["name" => "Section SA-1", "page" => 22],
    ["name" => "Section TRA-bannière", "page" => 23],
    ["name" => "Section TRA-1", "page" => 23],
    ["name" => "Section TRA-2", "page" => 23],
    ["name" => "Section TRA-3", "page" => 23],
    ["name" => "Section TRA-4", "page" => 23],
    ["name" => "Section RE-bannière", "page" => 24],
    ["name" => "Section RE-1", "page" => 24],
    ["name" => "Section RE-2", "page" => 24],
    ["name" => "Section BR-bannière", "page" => 25],
    ["name" => "Section BR-1", "page" => 25],
    ["name" => "Section BR-2", "page" => 25],
    ["name" => "Section BR-3", "page" => 25],
    ["name" => "Section RR-bannière", "page" => 26],
    ["name" => "Section RR-1", "page" => 26],
    ["name" => "Section RR-2", "page" => 26],
    ["name" => "Section RR-3", "page" => 26],
    ["name" => "Section RR-4", "page" => 26],
    ["name" => "Section RR-5", "page" => 26],
    ["name" => "Section RR-6", "page" => 26],
    ["name" => "Section FR-bannière", "page" => 27],
    ["name" => "Section FR-1", "page" => 27],
    ["name" => "Section FR-2", "page" => 27],
    ["name" => "Section FR-3", "page" => 27],
    ["name" => "Section FR-4", "page" => 27],
    ["name" => "Section FR-5", "page" => 27],
    ["name" => "Section FR-6", "page" => 27],
    ["name" => "Section FR-7", "page" => 27],
    ["name" => "Section CVL-bannière", "page" => 28],
    ["name" => "Section CVL-1", "page" => 28],
    ["name" => "Section CVL-2", "page" => 28],
    ["name" => "Section CVL-3", "page" => 28],
    ["name" => "Section CVL-4", "page" => 28],
    ["name" => "Section CVL-5", "page" => 28],
    ["name" => "Section CVL-6", "page" => 28],
    ["name" => "Section CVL-7", "page" => 28],
    ["name" => "Section CVL-8", "page" => 28],
    ["name" => "Section TBU-bannière", "page" => 29],
    ["name" => "Section TBU-1", "page" => 29],
    ["name" => "Section PA-bannière", "page" => 30],
    ["name" => "Section PA-1", "page" => 30],
    ["name" => "Section PAR-bannière", "page" => 31],
    ["name" => "Section PAR-1", "page" => 31],
    ["name" => "Section PAR-2", "page" => 31],
    ["name" => "Section PAR-3", "page" => 31],
    ["name" => "Section PAR-4", "page" => 31],
    ["name" => "Section BO-bannière", "page" => 32],
    ["name" => "Section BO-1", "page" => 32],
    ["name" => "Section BO-2", "page" => 32],
    ["name" => "Section BO-3", "page" => 32],
    ["name" => "Section BO-4", "page" => 32],
    ["name" => "Section BO-5", "page" => 32],
    ["name" => "Section BO-6", "page" => 32],
    ["name" => "Section FPO-bannière", "page" => 33],
    ["name" => "Section FPO-1", "page" => 33],
    ["name" => "Section FPO-2", "page" => 33],
    ["name" => "Section FPO-3", "page" => 33],
    ["name" => "Section FSSS-bannière", "page" => 34],
    ["name" => "Section FSSS-1", "page" => 34],
    ["name" => "Section FSSS-2", "page" => 34],
    ["name" => "Section FSSS-3", "page" => 34],
    ["name" => "Section DM-bannière", "page" => 35],
    ["name" => "Section DM-1", "page" => 35],
    ["name" => "Section DM-2", "page" => 35],
    ["name" => "Section DM-3", "page" => 35],
    ["name" => "Section DM-4", "page" => 35],
    ["name" => "Section DM-5", "page" => 35],
    ["name" => "Section DVC-bannière", "page" => 36],
    ["name" => "Section DVC-1", "page" => 36],
    ["name" => "Section DVC-2", "page" => 36],
    ["name" => "Section DVC-3", "page" => 36],
    ["name" => "Section DVC-4", "page" => 36],
    ["name" => "Section DVC-5", "page" => 36],
    ["name" => "Section bfqg-bannière", "page" => 37],
    ["name" => "Section bfqg-1", "page" => 37],
    ["name" => "Section bfqg-2", "page" => 37],
    ["name" => "Section bfqg-3", "page" => 37],
    ["name" => "Section bfqg-4", "page" => 37],
    ["name" => "Section bfqg-5", "page" => 37],
    ["name" => "Section bfqg-6", "page" => 37],
    ["name" => "Section bfqg-7", "page" => 37],
    ["name" => "Section bfqg-8", "page" => 37],
    ["name" => "Section bfqg-9", "page" => 37],
    ["name" => "Section SPQG-bannière", "page" => 38],
    ["name" => "Section SPQG-1", "page" => 38],
    ["name" => "Section SPQG-2", "page" => 38],
    ["name" => "Section SPQG-3", "page" => 38],
    ["name" => "Section SPQG-4", "page" => 38],
    ["name" => "Section SPQG-5", "page" => 38],
    ["name" => "Section SPQG-6", "page" => 38],
    ["name" => "Section SPQG-7", "page" => 38],
    ["name" => "Section SPQG-8", "page" => 38],
    ["name" => "Section SPQG-9", "page" => 38],
    ["name" => "Section SPQG-10", "page" => 38],
    ["name" => "Section SPQG-11", "page" => 38],
  ];

  public function load(ObjectManager $manager)
  {
    foreach (self::SECTIONS as $key => $section) {
      $name = $section['name'];
      $page = $section['page'];
      $newSection = new Section();
      $newSection->setName($name);
      $newSection->setSlug($name);
      $newSection->setPageId($this->getReference('page_' . $page));
      $manager->persist($newSection);
      $this->addReference('section_' . ($key + 1), $newSection);
    }

    $manager->flush();
  }

  public function getDependencies()
  {
    return [
      ElementBaseFixtures::class,
      ElementPhytoFixtures::class,
      ElementSabbatFixtures::class,
      RecetteTypeFixtures::class,
      ProfessionFixtures::class,
      StatutOrderFixtures::class,
      TypeRecueilFixtures::class,
      TypeAdresseFixtures::class,
      CategoryFixtures::class,
      FAQFixtures::class,
      TypeFixtures::class,
      CoachingVideoFixtures::class,
      FormationNumericFixtures::class,
      EvenementFixtures::class,
      TypeOptionFixtures::class,
      ProductFixtures::class,
      PromotionFixtures::class,
      StockFixtures::class,
      PageFixtures::class,
      TypeBlocFixtures::class,
      ConfigBlocFixtures::class
    ];
  }
}
